__all__ = ()

FACE_MESH_POINT__IRIS_RIGHT__INNER = 469
FACE_MESH_POINT__IRIS_RIGHT__TOP = 470
FACE_MESH_POINT__IRIS_RIGHT__OUTER = 471
FACE_MESH_POINT__IRIS_RIGHT__BOT = 472
FACE_MESH_POINT__IRIS_RIGHT__MID = 468

FACE_MESH_POINT__IRIS_LEFT__OUTER = 474
FACE_MESH_POINT__IRIS_LEFT__TOP = 475
FACE_MESH_POINT__IRIS_LEFT__INNER = 476
FACE_MESH_POINT__IRIS_LEFT__BOT = 477
FACE_MESH_POINT__IRIS_LEFT__MID = 473

FACE_MESH_POINT__EYE_OUTLINE_RIGHT__OUTER = 33
FACE_MESH_POINT__EYE_OUTLINE_RIGHT__TOP = 159
FACE_MESH_POINT__EYE_OUTLINE_RIGHT__TOP_OVER = 27
FACE_MESH_POINT__EYE_OUTLINE_RIGHT__INNER = 133
FACE_MESH_POINT__EYE_OUTLINE_RIGHT__BOT = 145
FACE_MESH_POINT__EYE_OUTLINE_RIGHT__BOT_OVER = 23

FACE_MESH_POINT__EYE_OUTLINE_LEFT__INNER = 362
FACE_MESH_POINT__EYE_OUTLINE_LEFT__TOP = 386
FACE_MESH_POINT__EYE_OUTLINE_LEFT__TOP_OVER = 257
FACE_MESH_POINT__EYE_OUTLINE_LEFT__OUTER = 263
FACE_MESH_POINT__EYE_OUTLINE_LEFT__BOT = 374
FACE_MESH_POINT__EYE_OUTLINE_LEFT__BOT_OVER = 253


FACE_MESH_POINT__NOSE_TIP = 19
FACE_MESH_POINT__FACE_LEFT_MOST = 454
FACE_MESH_POINT__FACE_RIGHT_MOST = 234

FACE_MESH_POINT__NOSE_RADIX = 168
FACE_MESH_POINT__FOREHEAD = 10

FACE_MESH_POINT__FOREHEAD__RIGHT = 103
FACE_MESH_POINT__FOREHEAD__LEFT = 332


FACE_MESH_POINT__MOUTH_LEFT = 292
FACE_MESH_POINT__MOUTH_RIGHT = 62

FACE_MESH_POINT__LIPS_LEFT = 291
FACE_MESH_POINT__LIPS_RIGHT = 61

FACE_MESH_POINT__MOUTH_TOP = 13
FACE_MESH_POINT__MOUTH_BOT = 14

FACE_MESH_POINT__LIPS_TOP = 0
FACE_MESH_POINT__LIPS_BOT = 17

FACE_MESH_POINT__CHEEKS_SMILE_LEFT__TOP_3 = 436
FACE_MESH_POINT__CHEEKS_SMILE_LEFT__MID_3 = 432
FACE_MESH_POINT__MOUTH_LEFT_MOST = 306
FACE_MESH_POINT__CHEEKS_SMILE_RIGHT__TOP_3 = 216
FACE_MESH_POINT__CHEEKS_SMILE_RIGHT__MID_3 = 212
FACE_MESH_POINT__MOUTH_RIGHT_MOST = 76
