__all__ = ()


POINT_BODY__HEAD_LEFT_MOST = 7
POINT_BODY__HEAD_RIGHT_MOST = 8

POINT_BODY__SHOULDER_LEFT = 11
POINT_BODY__SHOULDER_RIGHT = 12

POINT_BODY__ELBOW_LEFT = 13
POINT_BODY__ELBOW_RIGHT = 14

POINT_BODY__WRIST_LEFT = 15
POINT_BODY__WRIST_RIGHT = 16

POINT_BODY__HIP_LEFT = 23
POINT_BODY__HIP_RIGHT = 24

POINT_BODY__KNEE_LEFT = 25
POINT_BODY__KNEE_RIGHT = 26

POINT_BODY__ANKLE_LEFT = 27
POINT_BODY__ANKLE_RIGHT = 28
