__all__ = ()


POINT_BODY__HEAD_LEFT__MOST = 7
POINT_BODY__HEAD_RIGHT__MOST = 8

POINT_BODY__SHOULDER__LEFT = 11
POINT_BODY__SHOULDER__RIGHT = 12

POINT_BODY__ELBOW__LEFT = 13
POINT_BODY__ELBOW__RIGHT = 14

POINT_BODY__WRIST__LEFT = 15
POINT_BODY__WRIST__RIGHT = 16

POINT_BODY__HIP__LEFT = 23
POINT_BODY__HIP__RIGHT = 24

POINT_BODY__KNEE__LEFT = 25
POINT_BODY__KNEE__RIGHT = 26

POINT_BODY__ANKLE__LEFT = 27
POINT_BODY__ANKLE__RIGHT = 28
