__all__ = ()

POINT_FACE__IRIS_RIGHT__INNER = 469
POINT_FACE__IRIS_RIGHT__TOP = 470
POINT_FACE__IRIS_RIGHT__OUTER = 471
POINT_FACE__IRIS_RIGHT__BOT = 472
POINT_FACE__IRIS_RIGHT__MID = 468

POINT_FACE__IRIS_LEFT__OUTER = 474
POINT_FACE__IRIS_LEFT__TOP = 475
POINT_FACE__IRIS_LEFT__INNER = 476
POINT_FACE__IRIS_LEFT__BOT = 477
POINT_FACE__IRIS_LEFT__MID = 473

POINT_FACE__EYE_OUTLINE_RIGHT__OUTER = 33
POINT_FACE__EYE_OUTLINE_RIGHT__OUTER_1 = 130
POINT_FACE__EYE_OUTLINE_RIGHT__OUTER_2 = 226
POINT_FACE__EYE_OUTLINE_RIGHT__TOP = 159
POINT_FACE__EYE_OUTLINE_RIGHT__TOP_1 = 27
POINT_FACE__EYE_OUTLINE_RIGHT__INNER = 133
POINT_FACE__EYE_OUTLINE_RIGHT__INNER_1 = 243
POINT_FACE__EYE_OUTLINE_RIGHT__INNER_2 = 244
POINT_FACE__EYE_OUTLINE_RIGHT__BOT = 145
POINT_FACE__EYE_OUTLINE_RIGHT__BOT_1 = 23

POINT_FACE__EYE_OUTLINE_LEFT__INNER = 362
POINT_FACE__EYE_OUTLINE_LEFT__INNER_1 = 463
POINT_FACE__EYE_OUTLINE_LEFT__INNER_2 = 464
POINT_FACE__EYE_OUTLINE_LEFT__TOP = 386
POINT_FACE__EYE_OUTLINE_LEFT__TOP_1 = 257
POINT_FACE__EYE_OUTLINE_LEFT__OUTER = 263
POINT_FACE__EYE_OUTLINE_LEFT__OUTER_1 = 359
POINT_FACE__EYE_OUTLINE_LEFT__OUTER_2 = 446
POINT_FACE__EYE_OUTLINE_LEFT__BOT = 374
POINT_FACE__EYE_OUTLINE_LEFT__BOT_1 = 253


POINT_FACE__NOSE_TIP = 19
POINT_FACE__FACE_LEFT_MOST = 454
POINT_FACE__FACE_RIGHT_MOST = 234

POINT_FACE__NOSE_RADIX = 168
POINT_FACE__FOREHEAD = 10
POINT_FACE__FOREHEAD__LEFT_1 = 338
POINT_FACE__FOREHEAD__LEFT_2 = 297
POINT_FACE__FOREHEAD__RIGHT_1 = 109
POINT_FACE__FOREHEAD__RIGHT_2 = 67

POINT_FACE__FOREHEAD__RIGHT = 103
POINT_FACE__FOREHEAD__LEFT = 332


POINT_FACE__MOUTH_LEFT = 292
POINT_FACE__MOUTH_RIGHT = 62

POINT_FACE__LIPS_LEFT = 291
POINT_FACE__LIPS_RIGHT = 61

POINT_FACE__MOUTH_TOP = 13
POINT_FACE__MOUTH_BOT = 14

POINT_FACE__LIPS_TOP = 0
POINT_FACE__LIPS_BOT = 17

POINT_FACE__CHEEKS_SMILE_LEFT__TOP_3 = 436
POINT_FACE__CHEEKS_SMILE_LEFT__MID_3 = 432
POINT_FACE__MOUTH_LEFT_MOST = 306
POINT_FACE__CHEEKS_SMILE_RIGHT__TOP_3 = 216
POINT_FACE__CHEEKS_SMILE_RIGHT__MID_3 = 212
POINT_FACE__MOUTH_RIGHT_MOST = 76

POINT_FACE__EYEBROW_LEFT__TOP = 336
POINT_FACE__EYEBROW_LEFT__BOT = 285
POINT_FACE__EYEBROW_RIGHT__TOP = 107
POINT_FACE__EYEBROW_RIGHT__BOT = 55
POINT_FACE__EYEBROW_RIGHT__BOT_3 = 52
POINT_FACE__EYEBROW_RIGHT__BOT_5 = 46

POINT_FACE__CHIN = 152
